package com.example.george.myapplication;

import android.os.Bundle;
import android.preference.PreferenceActivity;

public class PokerShow extends PreferenceActivity{
    final static int[] m_pokerImages = new int[]{
            R.drawable.poker1_1,
            R.drawable.poker1_2,
            R.drawable.poker1_3,
            R.drawable.poker1_4,
            R.drawable.poker2_1,
            R.drawable.poker2_2,
            R.drawable.poker2_3,
            R.drawable.poker2_4,
            R.drawable.poker3_1,
            R.drawable.poker3_2,
            R.drawable.poker3_3,
            R.drawable.poker3_4,
            R.drawable.poker4_1,
            R.drawable.poker4_2,
            R.drawable.poker4_3,
            R.drawable.poker4_4,
            R.drawable.poker5_1,
            R.drawable.poker5_2,
            R.drawable.poker5_3,
            R.drawable.poker5_4,
            R.drawable.poker6_1,
            R.drawable.poker6_2,
            R.drawable.poker6_3,
            R.drawable.poker6_4,
            R.drawable.poker7_1,
            R.drawable.poker7_2,
            R.drawable.poker7_3,
            R.drawable.poker7_4,
            R.drawable.poker8_1,
            R.drawable.poker8_2,
            R.drawable.poker8_3,
            R.drawable.poker8_4,
            R.drawable.poker9_1,
            R.drawable.poker9_2,
            R.drawable.poker9_3,
            R.drawable.poker9_4,
            R.drawable.poker10_1,
            R.drawable.poker10_2,
            R.drawable.poker10_3,
            R.drawable.poker10_4,
            R.drawable.poker11_1,
            R.drawable.poker11_2,
            R.drawable.poker11_3,
            R.drawable.poker11_4,
            R.drawable.poker12_1,
            R.drawable.poker12_2,
            R.drawable.poker12_3,
            R.drawable.poker12_4,
            R.drawable.poker13_1,
            R.drawable.poker13_2,
            R.drawable.poker13_3,
            R.drawable.poker13_4,
            R.drawable.poker14_1,
            R.drawable.poker15_1,
    };
    final static String[] m_pokerNames = new String[]{
            "SpadesA",
            "HeartsA",
            "ClubsA",
            "DiamondsA",
            "Spades2",
            "Hearts2",
            "Clubs2",
            "Diamonds2",
            "Spades3",
            "Hearts3",
            "Clubs3",
            "Diamonds3",
            "Spades4",
            "Hearts4",
            "Clubs4",
            "Diamonds4",
            "Spades5",
            "Hearts5",
            "Clubs5",
            "Diamonds5",
            "Spades6",
            "Hearts6",
            "Clubs6",
            "Diamonds6",
            "Spades7",
            "Hearts7",
            "Clubs7",
            "Diamonds7",
            "Spades8",
            "Hearts8",
            "Clubs8",
            "Diamonds8",
            "Spades9",
            "Hearts9",
            "Clubs9",
            "Diamonds9",
            "Spades10",
            "Hearts10",
            "Clubs10",
            "Diamonds10",
            "SpadesJ",
            "HeartsJ",
            "ClubsJ",
            "DiamondsJ",
            "SpadesQ",
            "HeartsQ",
            "ClubsQ",
            "DiamondsQ",
            "SpadesK",
            "HeartsK",
            "ClubsK",
            "DiamondsK",
            "Little Joker",
            "Big Joker",
    };
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        addPreferencesFromResource(R.xml.mainlist);
    }

}
